name: CI/CD after file compress

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mini-chrome repository
        uses: actions/checkout@v2

      - name: Setup Node.js on runner
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Log raw application size
        run: du -h -d 1 ./out/*

      - name: Compress Darwin x64
        run: cd out && tar -czvf ../download/Mini-Chrome-darwin-x64.tar.gz './Mini Chrome-darwin-x64'

      - name: Compress Darwin ARM 64
        run: cd out && tar -czvf ../download/Mini-Chrome-darwin-arm64.tar.gz './Mini Chrome-darwin-arm64'

      - name: Compress MAS x64
        run: cd out && tar -czvf ../download/Mini-Chrome-mas-x64.tar.gz './Mini Chrome-mas-x64'

      - name: Compress MAS ARM 64
        run: cd out && tar -czvf ../download/Mini-Chrome-mas-arm64.tar.gz './Mini Chrome-mas-arm64'

      - name: Log compressed file size
        run: du -h -d 1 ./download/*

      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./download
