name: CI/CD after file compress

on:
  push:
    branches: [master, test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mini-chrome repository
        uses: actions/checkout@v2

      - name: Setup Node.js on runner
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - run: cd download && ls -lh

      - name: Darwin x64
        uses: vimtor/action-zip@v1
        with:
          files: "out/Mini Chrome-darwin-x64/"
          dest: "download/Mini Chrome-darwin-x64.zip"

      - name: Darwin ARM 64
        uses: vimtor/action-zip@v1
        with:
          files: "out/Mini Chrome-darwin-arm64/"
          dest: "download/Mini Chrome-darwin-arm64.zip"

      - name: MAS x64
        uses: vimtor/action-zip@v1
        with:
          files: "out/Mini Chrome-mas-x64/"
          dest: "download/Mini Chrome-mas-x64.zip"

      - name: MAS ARM 64
        uses: vimtor/action-zip@v1
        with:
          files: "out/Mini Chrome-mas-arm64/"
          dest: "download/Mini Chrome-mas-arm64.zip"

      - run: cd download && ls -lh

      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./download
